// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as Menu from "./Menu.js";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Header from "./Header.js";
import * as Popover from "./Popover.js";
import * as Calendar from "./Calendar.js";
import * as Electron from "electron";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Add_months from "date-fns/add_months";
import * as Sub_months from "date-fns/sub_months";

var component = ReasonReact.reducerComponent("Index");

var container_styles = {
  height: "100%"
};

var caret_styles = {
  borderRight: "solid transparent 10px",
  borderBottom: "solid #000 10px",
  borderLeft: "solid transparent 10px",
  content: "' '",
  height: "10px",
  left: "50%",
  marginLeft: "-10px",
  position: "absolute",
  top: "0",
  width: "0"
};

function onNextMonth() {
  return /* NextMonth */0;
}

function onLastMonth() {
  return /* PreviousMonth */1;
}

function resetDate() {
  return /* ResetDate */2;
}

function updateAvailable() {
  return /* UpdateAvailable */3;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (param) {
      var reduce = param[/* reduce */1];
      Electron.ipcRenderer.on("background-update", Curry._1(reduce, resetDate));
      Electron.ipcRenderer.on("update-ready", Curry._1(reduce, updateAvailable));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */2];
      var date = state[/* date */0];
      var update_available = state[/* updateAvailable */1];
      return React.createElement("div", {
                  style: container_styles
                }, ReasonReact.element(/* None */0, /* None */0, Popover.make(/* array */[
                          ReasonReact.element(/* None */0, /* None */0, Header.make(param[/* reduce */1], date, onNextMonth, onLastMonth, resetDate, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Calendar.make(date, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Menu.make(update_available, /* array */[]))
                        ])), React.createElement("div", {
                      style: caret_styles
                    }));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* date */Date.now(),
              /* updateAvailable : false */0
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      switch (action) {
        case 0 : 
            return /* Update */Block.__(0, [/* record */[
                        /* date */Add_months(state[/* date */0], 1),
                        /* updateAvailable */state[/* updateAvailable */1]
                      ]]);
        case 1 : 
            return /* Update */Block.__(0, [/* record */[
                        /* date */Sub_months(state[/* date */0], 1),
                        /* updateAvailable */state[/* updateAvailable */1]
                      ]]);
        case 2 : 
            return /* Update */Block.__(0, [/* record */[
                        /* date */Date.now(),
                        /* updateAvailable */state[/* updateAvailable */1]
                      ]]);
        case 3 : 
            return /* Update */Block.__(0, [/* record */[
                        /* date */state[/* date */0],
                        /* updateAvailable : true */1
                      ]]);
        
      }
    });
  return newrecord;
}

export {
  component ,
  container_styles ,
  caret_styles ,
  onNextMonth ,
  onLastMonth ,
  resetDate ,
  updateAvailable ,
  make ,
  
}
/* component Not a pure module */
