// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Electron from "electron";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("CalendarHeader");

function weekdays() {
  var day = Electron.remote.getGlobal("global").firstWeekday;
  var index = day - 1 | 0;
  var list = /* array */[
    "S",
    "M",
    "T",
    "W",
    "T",
    "F",
    "S"
  ];
  var before = $$Array.sub(list, index, list.length - index | 0);
  var after = $$Array.sub(list, 0, index);
  return $$Array.append(before, after);
}

var column_styles = {
  color: "#FFF",
  fontSize: "0.725rem",
  padding: "0.3em 0",
  textAlign: "center",
  textTransform: "uppercase",
  width: "14.28%",
  opacity: "0.5"
};

function column_header(idx, day) {
  return React.createElement("th", {
              key: String(idx),
              style: column_styles
            }, day);
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("thead", undefined, React.createElement("tr", undefined, $$Array.mapi(column_header, weekdays(/* () */0))));
    });
  return newrecord;
}

export {
  component ,
  weekdays ,
  column_styles ,
  column_header ,
  make ,
  
}
/* component Not a pure module */
