// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as React          from "react";
import * as ReasonReact    from "reason-react/lib/es6/src/reasonReact.js";
import * as CalendarBody   from "./CalendarBody.js";
import * as CalendarHeader from "./CalendarHeader.js";

var component = ReasonReact.statelessComponent("Calendar");

var calendar_styles = {
  padding: "0 1em",
  width: "100%"
};

function make(date, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("table", {
                  style: calendar_styles
                }, ReasonReact.element(/* None */0, /* None */0, CalendarHeader.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, CalendarBody.make(date, /* array */[])));
    });
  return newrecord;
}

export {
  component       ,
  calendar_styles ,
  make            ,
  
}
/* component Not a pure module */
