// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$Array     from "bs-platform/lib/es6/array.js";
import * as React       from "react";
import * as Pervasives  from "bs-platform/lib/es6/pervasives.js";
import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

var component = ReasonReact.statelessComponent("CalendarHeader");

var weekdays = /* array */[
  "S",
  "M",
  "T",
  "W",
  "T",
  "F",
  "S"
];

var column_styles = {
  color: "#FFF",
  fontSize: "0.725rem",
  padding: "0.3em 0",
  textAlign: "center",
  textTransform: "uppercase",
  width: "14.28%",
  opacity: "0.5"
};

function column_header(idx, day) {
  return React.createElement("th", {
              key: Pervasives.string_of_int(idx),
              style: column_styles
            }, day);
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("thead", undefined, React.createElement("tr", undefined, $$Array.mapi(column_header, weekdays)));
    });
  return newrecord;
}

export {
  component     ,
  weekdays      ,
  column_styles ,
  column_header ,
  make          ,
  
}
/* component Not a pure module */
