// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

import * as Get_time              from "date-fns/get_time";
import * as Set_date_unsafe       from "date-fns/set_date";
import * as Start_of_month_unsafe from "date-fns/start_of_month";

var PackageJSON = /* module */[];

var Electron = /* module */[];

var Raven = /* module */[];

var Process = /* module */[];

var DOM = /* module */[];

function set_date(date, $$int) {
  return Get_time(Set_date_unsafe(date, $$int));
}

function start_of_month(date) {
  return Get_time(Start_of_month_unsafe(date));
}

var DateFns = /* module */[
  /* set_date */set_date,
  /* start_of_month */start_of_month
];

export {
  PackageJSON ,
  Electron    ,
  Raven       ,
  Process     ,
  DOM         ,
  DateFns     ,
  
}
/* date-fns/get_time Not a pure module */
