// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as RavenJs from "raven-js";
import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as PackageJSON from "../../../package.json";

if (process.env.NODE_ENV === "production") {
  RavenJs.config("https://970be29a9988418ebe1215c7f12223ef@sentry.io/204281", {
          release: PackageJSON.version
        }).install();
}

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
