// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Electron from "electron";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

function quit_app() {
  Electron.ipcRenderer.send("quit-app");
  return /* () */0;
}

function update_app() {
  Electron.ipcRenderer.send("install-update");
  return /* () */0;
}

function show_about() {
  Electron.ipcRenderer.send("show-about");
  return /* () */0;
}

var menu_styles = {
  bottom: "5px",
  display: "flex",
  height: "26px",
  marginBottom: "0.5em",
  padding: "0 1em",
  position: "absolute",
  textAlign: "right",
  width: "100%",
  borderBottomLeftRadius: "5px",
  borderBottomRightRadius: "5px",
  alignItems: "center",
  justifyContent: "space-between"
};

var quit_styles = {
  cursor: "pointer",
  display: "inline-block",
  height: "15px",
  marginLeft: "0.5em",
  textDecoration: "none",
  width: "15px"
};

var show_about_styles = {
  cursor: "pointer",
  display: "inline-block",
  height: "15px",
  textDecoration: "none",
  width: "15px"
};

var update_styles = {
  color: "#FFF",
  fontSize: "12px"
};

var link_styles = {
  color: "#F012BE",
  fontSize: "12px",
  textDecoration: "none"
};

var component = ReasonReact.statelessComponent("Menu");

var power = React.createElement("svg", {
      fill: "none",
      stroke: "#FFF",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "2",
      viewBox: "0 0 24 24"
    }, React.createElement("path", {
          d: "M18.36 6.64a9 9 0 1 1-12.73 0"
        }), React.createElement("line", {
          x1: "12",
          x2: "12",
          y1: "2",
          y2: "12"
        }));

var info = React.createElement("svg", {
      fill: "none",
      stroke: "#FFF",
      strokeLinecap: "round",
      strokeLinejoin: "round",
      strokeWidth: "2",
      viewBox: "0 0 24 24"
    }, React.createElement("circle", {
          cx: "12",
          cy: "12",
          r: "10"
        }), React.createElement("line", {
          x1: "12",
          x2: "12",
          y1: "16",
          y2: "12"
        }), React.createElement("line", {
          x1: "12",
          x2: "12",
          y1: "8",
          y2: "8"
        }));

function make(update_available, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var update_el = update_available !== 0 ? React.createElement("span", {
              style: update_styles
            }, "An update is available. ", React.createElement("a", {
                  style: link_styles,
                  href: "#",
                  onClick: update_app
                }, "Install now")) : "";
      return React.createElement("div", {
                  style: menu_styles
                }, React.createElement("span", {
                      style: update_styles
                    }, update_el), React.createElement("div", undefined, React.createElement("a", {
                          style: show_about_styles,
                          href: "#",
                          onClick: show_about
                        }, info), React.createElement("a", {
                          style: quit_styles,
                          href: "#",
                          onClick: quit_app
                        }, power)));
    });
  return newrecord;
}

export {
  quit_app ,
  update_app ,
  show_about ,
  menu_styles ,
  quit_styles ,
  show_about_styles ,
  update_styles ,
  link_styles ,
  component ,
  power ,
  info ,
  make ,
  
}
/* component Not a pure module */
