// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

import * as ReasonReact from "reason-react/lib/es6/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Popover");

var popover_styles = {
  backgroundColor: "#000",
  cursor: "default",
  height: "auto",
  margin: "0 auto",
  marginTop: "10px",
  padding: "0",
  paddingBottom: "1px",
  position: "relative",
  width: "300px",
  borderRadius: "5px"
};

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement("div", {
                  style: popover_styles
                }, children);
    });
  return newrecord;
}

export {
  component      ,
  popover_styles ,
  make           ,
  
}
/* component Not a pure module */
