// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Week");

var week_styles = {
  color: "#FFF",
  textAlign: "center"
};

function day_styles(is_today) {
  return {
          color: is_today !== 0 ? "#F012BE" : "#FFF",
          fontWeight: "700",
          padding: "0.25em 0"
        };
}

function weekday(idx, date) {
  var match = date[0];
  var date_element = match ? String(match[0]) : "";
  return React.createElement("td", {
              key: String(idx),
              style: day_styles(date[1])
            }, date_element);
}

function make(week, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var weekday_elements = $$Array.mapi(weekday, week);
      return ReasonReact.createDomElement("tr", {
                  style: week_styles
                }, weekday_elements);
    });
  return newrecord;
}

export {
  component ,
  week_styles ,
  day_styles ,
  weekday ,
  make ,
  
}
/* component Not a pure module */
