// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Menu        = require("./menu.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Header      = require("./header.js");
var Popover     = require("./popover.js");
var Calendar    = require("./calendar.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var Add_months  = require("date-fns/add_months");
var Sub_months  = require("date-fns/sub_months");

var component = ReasonReact.statefulComponent("Index");

var container_styles = {
  height: "255px"
};

var caret_styles = {
  borderRight: "solid transparent 10px",
  borderBottom: "solid #000 10px",
  borderLeft: "solid transparent 10px",
  content: "' '",
  height: "10px",
  left: "50%",
  marginLeft: "-13px",
  position: "absolute",
  top: "0",
  width: "0"
};

function onNextMonth(_, self) {
  return /* Update */Block.__(0, [Add_months(self[/* state */3], 1)]);
}

function onLastMonth(_, self) {
  return /* Update */Block.__(0, [Sub_months(self[/* state */3], 1)]);
}

function reset_date(_, _$1) {
  if (document.hidden) {
    return /* Update */Block.__(0, [Date.now()]);
  } else {
    return /* NoUpdate */0;
  }
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      var date = self[/* state */3];
      document.addEventListener("visibilitychange", Curry._1(self[/* update */2], reset_date));
      return React.createElement("div", {
                  style: container_styles
                }, ReasonReact.element(/* None */0, /* None */0, Popover.make(/* array */[
                          ReasonReact.element(/* None */0, /* None */0, Header.make(self, date, onNextMonth, onLastMonth, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Calendar.make(date, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Menu.make(/* array */[]))
                        ])), React.createElement("div", {
                      style: caret_styles
                    }));
    });
  newrecord[/* initialState */10] = (function () {
      return Date.now();
    });
  return newrecord;
}

exports.component        = component;
exports.container_styles = container_styles;
exports.caret_styles     = caret_styles;
exports.onNextMonth      = onNextMonth;
exports.onLastMonth      = onLastMonth;
exports.reset_date       = reset_date;
exports.make             = make;
/* component Not a pure module */
