// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Electron    = require("electron");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function show_config_menu() {
  Electron.ipcRenderer.send("show-config-menu");
  return /* () */0;
}

var component = ReasonReact.statelessComponent("Index");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "container"
                }, React.createElement("div", {
                      className: "popover"
                    }, React.createElement("div", {
                          className: "header"
                        }, React.createElement("h1", undefined, "Hello World")), React.createElement("div", {
                          className: "menu"
                        }, React.createElement("a", {
                              className: "config",
                              href: "#",
                              onClick: show_config_menu
                            }))));
    });
  return newrecord;
}

exports.show_config_menu = show_config_menu;
exports.component        = component;
exports.make             = make;
/* component Not a pure module */
