// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Menu        = require("./menu.js");
var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Header      = require("./header.js");
var Popover     = require("./popover.js");
var Calendar    = require("./calendar.js");
var Electron    = require("electron");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var Add_months  = require("date-fns/add_months");
var Sub_months  = require("date-fns/sub_months");

var component = ReasonReact.statefulComponent("Index");

var container_styles = {
  height: "100%"
};

var caret_styles = {
  borderRight: "solid transparent 10px",
  borderBottom: "solid #000 10px",
  borderLeft: "solid transparent 10px",
  content: "' '",
  height: "10px",
  left: "50%",
  marginLeft: "-10px",
  position: "absolute",
  top: "0",
  width: "0"
};

function onNextMonth(_, param) {
  var state = param[/* state */3];
  return /* Update */Block.__(0, [/* record */[
              /* date */Add_months(state[/* date */0], 1),
              /* updateAvailable */state[/* updateAvailable */1]
            ]]);
}

function onLastMonth(_, param) {
  var state = param[/* state */3];
  return /* Update */Block.__(0, [/* record */[
              /* date */Sub_months(state[/* date */0], 1),
              /* updateAvailable */state[/* updateAvailable */1]
            ]]);
}

function resetDate(_, param) {
  return /* Update */Block.__(0, [/* record */[
              /* date */Date.now(),
              /* updateAvailable */param[/* state */3][/* updateAvailable */1]
            ]]);
}

function updateAvailable(_, param) {
  return /* Update */Block.__(0, [/* record */[
              /* date */param[/* state */3][/* date */0],
              /* updateAvailable : true */1
            ]]);
}

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (param) {
      var update = param[/* update */2];
      Electron.ipcRenderer.on("background-update", Curry._1(update, resetDate));
      Electron.ipcRenderer.on("update-available", Curry._1(update, updateAvailable));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var state = param[/* state */3];
      var date = state[/* date */0];
      var update_available = state[/* updateAvailable */1];
      return React.createElement("div", {
                  style: container_styles
                }, ReasonReact.element(/* None */0, /* None */0, Popover.make(/* array */[
                          ReasonReact.element(/* None */0, /* None */0, Header.make(param[/* update */2], date, onNextMonth, onLastMonth, resetDate, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Calendar.make(date, /* array */[])),
                          ReasonReact.element(/* None */0, /* None */0, Menu.make(update_available, /* array */[]))
                        ])), React.createElement("div", {
                      style: caret_styles
                    }));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* date */Date.now(),
              /* updateAvailable : false */0
            ];
    });
  return newrecord;
}

exports.component        = component;
exports.container_styles = container_styles;
exports.caret_styles     = caret_styles;
exports.onNextMonth      = onNextMonth;
exports.onLastMonth      = onLastMonth;
exports.resetDate        = resetDate;
exports.updateAvailable  = updateAvailable;
exports.make             = make;
/* component Not a pure module */
