// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("CalendarHeader");

var weekdays = /* array */[
  "S",
  "M",
  "T",
  "W",
  "T",
  "F",
  "S"
];

var column_styles = {
  color: "#FFF",
  fontSize: "0.725rem",
  padding: "0.3em 0",
  textAlign: "center",
  textTransform: "uppercase",
  width: "14.28%",
  opacity: "0.5"
};

function column_header(idx, day) {
  return React.createElement("th", {
              key: Pervasives.string_of_int(idx),
              style: column_styles
            }, day);
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("thead", undefined, React.createElement("tr", undefined, $$Array.mapi(column_header, weekdays)));
    });
  return newrecord;
}

exports.component     = component;
exports.weekdays      = weekdays;
exports.column_styles = column_styles;
exports.column_header = column_header;
exports.make          = make;
/* component Not a pure module */
