// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React          = require("react");
var ReasonReact    = require("reason-react/lib/js/src/reasonReact.js");
var CalendarBody   = require("./calendarBody.js");
var CalendarHeader = require("./calendarHeader.js");

var component = ReasonReact.statelessComponent("Calendar");

var calendar_styles = {
  padding: "0 1em",
  width: "100%"
};

function make(date, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("table", {
                  style: calendar_styles
                }, ReasonReact.element(/* None */0, /* None */0, CalendarHeader.make(/* array */[])), ReasonReact.element(/* None */0, /* None */0, CalendarBody.make(date, /* array */[])));
    });
  return newrecord;
}

exports.component       = component;
exports.calendar_styles = calendar_styles;
exports.make            = make;
/* component Not a pure module */
