// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Get_time              = require("date-fns/get_time");
var Set_date_unsafe       = require("date-fns/set_date");
var Start_of_month_unsafe = require("date-fns/start_of_month");

function set_date(date, $$int) {
  return Get_time(Set_date_unsafe(date, $$int));
}

function start_of_month(date) {
  return Get_time(Start_of_month_unsafe(date));
}

exports.set_date       = set_date;
exports.start_of_month = start_of_month;
/* date-fns/get_time Not a pure module */
