// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Get_time              = require("date-fns/get_time");
var Set_date_unsafe       = require("date-fns/set_date");
var Start_of_month_unsafe = require("date-fns/start_of_month");

var PackageJSON = /* module */[];

var Electron = /* module */[];

var Raven = /* module */[];

var Process = /* module */[];

var DOM = /* module */[];

function set_date(date, $$int) {
  return Get_time(Set_date_unsafe(date, $$int));
}

function start_of_month(date) {
  return Get_time(Start_of_month_unsafe(date));
}

var DateFns = /* module */[
  /* set_date */set_date,
  /* start_of_month */start_of_month
];

exports.PackageJSON = PackageJSON;
exports.Electron    = Electron;
exports.Raven       = Raven;
exports.Process     = Process;
exports.DOM         = DOM;
exports.DateFns     = DateFns;
/* date-fns/get_time Not a pure module */
