// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var Format_date = require("date-fns/format");

var component = ReasonReact.statelessComponent("Header");

var header_styles = {
  backgroundColor: "#000",
  height: "40px",
  marginBottom: "10px",
  paddingTop: "0px",
  textAlign: "center",
  borderTopLeftRadius: "4px",
  borderTopRightRadius: "4px"
};

var header_text_styles = {
  color: "#fff",
  fontSize: "22px",
  lineHeight: "40px",
  margin: "0"
};

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var current_date = Date.now();
      var current_month = Format_date(current_date, "MMMM YYYY");
      return React.createElement("div", {
                  style: header_styles
                }, React.createElement("h1", {
                      style: header_text_styles
                    }, current_month));
    });
  return newrecord;
}

exports.component          = component;
exports.header_styles      = header_styles;
exports.header_text_styles = header_text_styles;
exports.make               = make;
/* component Not a pure module */
