// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var Format_date = require("date-fns/format");

var component = ReasonReact.statelessComponent("Header");

var header_styles = {
  backgroundColor: "#000",
  display: "flex",
  marginBottom: "10px",
  paddingTop: "0px",
  textAlign: "center",
  borderTopLeftRadius: "4px",
  borderTopRightRadius: "4px",
  alignItems: "center"
};

var header_text_styles = {
  color: "#fff",
  fontSize: "22px",
  lineHeight: "40px",
  margin: "0",
  padding: "0.5em 0",
  flexGrow: "2"
};

var navigation_styles = {
  color: "#FFF",
  fontSize: "1.2rem",
  textDecoration: "none",
  width: "50px"
};

function make(self, date, onNextMonth, onLastMonth, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var current_month = Format_date(date, "MMMM YYYY");
      return React.createElement("div", {
                  style: header_styles
                }, React.createElement("a", {
                      style: navigation_styles,
                      href: "#",
                      onClick: Curry._1(self[/* update */2], onLastMonth),
                      dangerouslySetInnerHTML: {
                        __html: "&larr;"
                      }
                    }), React.createElement("h1", {
                      style: header_text_styles
                    }, current_month), React.createElement("a", {
                      style: navigation_styles,
                      href: "#",
                      onClick: Curry._1(self[/* update */2], onNextMonth),
                      dangerouslySetInnerHTML: {
                        __html: "&rarr;"
                      }
                    }));
    });
  return newrecord;
}

exports.component          = component;
exports.header_styles      = header_styles;
exports.header_text_styles = header_text_styles;
exports.navigation_styles  = navigation_styles;
exports.make               = make;
/* component Not a pure module */
