// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var App         = require("./app.js");
var RavenJs     = require("raven-js");
var ReactDOMRe  = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");
var PackageJSON = require("../../../package.json");

if (process.env.NODE_ENV === "production") {
  RavenJs.config("https://970be29a9988418ebe1215c7f12223ef@sentry.io/204281", {
          release: PackageJSON.version
        }).install();
}

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App.make(/* array */[])), "app");

/*  Not a pure module */
