// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React      = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement("h1", undefined, "Hello World!"), "app");

/*  Not a pure module */
