// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Electron    = require("electron");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function quit_app() {
  Electron.ipcRenderer.send("quit-app");
  return /* () */0;
}

var menu_styles = {
  bottom: "0",
  height: "26px",
  position: "absolute",
  textAlign: "right",
  width: "100%",
  borderBottomLeftRadius: "5px",
  borderBottomRightRadius: "5px"
};

var config_styles = {
  cursor: "default",
  display: "inline-block",
  height: "15px",
  marginRight: "10px",
  textDecoration: "none",
  width: "14px"
};

var component = ReasonReact.statelessComponent("Menu");

var cog = React.createElement("svg", {
      height: "15px",
      width: "14px",
      viewBox: "0 0 14 15"
    }, React.createElement("g", {
          fill: "none",
          fillRule: "evenodd",
          stroke: "none",
          strokeWidth: "1"
        }, React.createElement("rect", {
              height: "8",
              width: "2",
              fill: "#FFF",
              rx: "1",
              x: "6",
              y: "0"
            }), React.createElement("path", {
              d: "M2.99266802,3.53436007 C1.76942592,4.63279117 1,6.22654106 1,8 C1,11.3137085 3.6862915,14 7,14 C10.3137085,14 13,11.3137085 13,8 C13,6.21282738 12.2186285,4.60815384 10.9788737,3.50896745",
              stroke: "#FFF",
              strokeLinecap: "round",
              strokeWidth: "2"
            })));

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: menu_styles
                }, React.createElement("a", {
                      style: config_styles,
                      href: "#",
                      onClick: quit_app
                    }, cog));
    });
  return newrecord;
}

exports.quit_app      = quit_app;
exports.menu_styles   = menu_styles;
exports.config_styles = config_styles;
exports.component     = component;
exports.cog           = cog;
exports.make          = make;
/* component Not a pure module */
