// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var Electron    = require("electron");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function show_config_menu() {
  Electron.ipcRenderer.send("show-config-menu");
  return /* () */0;
}

var menu_styles = {
  bottom: "0",
  height: "26px",
  position: "absolute",
  textAlign: "right",
  width: "100%",
  borderBottomLeftRadius: "5px",
  borderBottomRightRadius: "5px"
};

var config_styles = {
  background: "transparent url(Design/cog.png) right center no-repeat",
  color: "#8d8d8d",
  cursor: "default",
  display: "inline-block",
  height: "18px",
  marginRight: "10px",
  textDecoration: "none",
  width: "18px",
  opacity: "0.7",
  backgroundSize: "100% 100%"
};

var component = ReasonReact.statelessComponent("Menu");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  style: menu_styles
                }, React.createElement("a", {
                      style: config_styles,
                      href: "#",
                      onClick: show_config_menu
                    }));
    });
  return newrecord;
}

exports.show_config_menu = show_config_menu;
exports.menu_styles      = menu_styles;
exports.config_styles    = config_styles;
exports.component        = component;
exports.make             = make;
/* component Not a pure module */
