// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Popover");

var popover_styles = {
  backgroundColor: "#000",
  cursor: "default",
  height: "270px",
  margin: "0 auto",
  marginTop: "10px",
  padding: "0",
  position: "relative",
  width: "300px",
  borderRadius: "5px"
};

function make(children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.createDomElement("div", {
                  style: popover_styles
                }, children);
    });
  return newrecord;
}

exports.component      = component;
exports.popover_styles = popover_styles;
exports.make           = make;
/* component Not a pure module */
