// Generated by BUCKLESCRIPT VERSION 1.8.2, PLEASE EDIT WITH CARE
'use strict';

var $$Array     = require("bs-platform/lib/js/array.js");
var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("Week");

var week_styles = {
  color: "#FFF",
  textAlign: "center"
};

function day_styles(is_today) {
  return {
          color: is_today !== 0 ? "#F012BE" : "#FFF",
          fontWeight: "700",
          padding: "0.25em 0"
        };
}

function weekday(idx, date) {
  var match = date[0];
  var date_element = match ? Pervasives.string_of_int(match[0]) : "";
  return React.createElement("td", {
              key: Pervasives.string_of_int(idx),
              style: day_styles(date[1])
            }, date_element);
}

function make(week, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var weekday_elements = $$Array.mapi(weekday, week);
      return ReasonReact.createDomElement("tr", {
                  style: week_styles
                }, weekday_elements);
    });
  return newrecord;
}

exports.component   = component;
exports.week_styles = week_styles;
exports.day_styles  = day_styles;
exports.weekday     = weekday;
exports.make        = make;
/* component Not a pure module */
