name: CI

on: [push]

jobs:
  test:
    name: Test the project on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          NODE_ENV: test
        run: npm run test:coverage
